
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 10 05:00:25 GMT 2024
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 5;
  public static final int EXIT_COMMAND = 6;
  public static final int NUMBER = 9;
  public static final int SEMI = 3;
  public static final int EQ = 8;
  public static final int EOF = 0;
  public static final int PLUS = 4;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int PRINT = 7;
}

