
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int EXIT_COMMAND = 5;
  public static final int NUMBER = 10;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int EQ = 7;
  public static final int ID = 9;
  public static final int error = 1;
  public static final int PRINT = 6;
  public static final int NEWLINE = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "EXIT_COMMAND",
  "PRINT",
  "EQ",
  "NEWLINE",
  "ID",
  "NUMBER"
  };
}

