
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 17 05:12:38 GMT 2024
//----------------------------------------------------

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Mar 17 05:12:38 GMT 2024
  */
public class CoolParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public CoolParser() {super();}

  /** Constructor which sets the default scanner. */
  public CoolParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public CoolParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\051\000\002\002\003\000\002\002\004\000\002\003" +
    "\003\000\002\003\004\000\002\004\010\000\002\004\012" +
    "\000\002\004\010\000\002\006\006\000\002\006\014\000" +
    "\002\006\007\000\002\006\014\000\002\006\002\000\002" +
    "\007\005\000\002\007\007\000\002\007\002\000\002\011" +
    "\003\000\002\011\005\000\002\010\003\000\002\010\003" +
    "\000\002\010\003\000\002\010\003\000\002\010\005\000" +
    "\002\010\005\000\002\010\005\000\002\010\005\000\002" +
    "\010\005\000\002\010\005\000\002\010\005\000\002\010" +
    "\004\000\002\010\012\000\002\010\010\000\002\010\006" +
    "\000\002\010\011\000\002\010\007\000\002\010\012\000" +
    "\002\010\007\000\002\010\004\000\002\010\005\000\002" +
    "\012\010\000\002\012\011\000\002\005\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\207\000\004\004\007\001\002\000\006\002\001\004" +
    "\007\001\002\000\004\002\210\001\002\000\006\002\uffff" +
    "\004\uffff\001\002\000\006\003\011\055\010\001\002\000" +
    "\006\011\177\050\176\001\002\000\004\050\012\001\002" +
    "\000\006\051\ufff6\056\014\001\002\000\006\051\161\056" +
    "\160\001\002\000\006\044\015\045\016\001\002\000\004" +
    "\055\156\001\002\000\010\042\ufff3\046\ufff3\056\020\001" +
    "\002\000\006\042\023\046\024\001\002\000\004\044\021" +
    "\001\002\000\004\055\022\001\002\000\006\042\ufff5\046" +
    "\ufff5\001\002\000\004\056\153\001\002\000\004\044\025" +
    "\001\002\000\004\055\026\001\002\000\004\050\027\001" +
    "\002\000\030\007\036\012\043\017\031\020\040\024\033" +
    "\027\042\050\030\052\034\053\032\054\035\056\037\001" +
    "\002\000\030\007\036\012\043\017\031\020\040\024\033" +
    "\027\042\050\030\052\034\053\032\054\035\056\037\001" +
    "\002\000\030\007\036\012\043\017\031\020\040\024\033" +
    "\027\042\050\030\052\034\053\032\054\035\056\037\001" +
    "\002\000\052\005\ufff0\006\ufff0\010\ufff0\014\ufff0\015\ufff0" +
    "\016\ufff0\022\ufff0\030\ufff0\032\ufff0\033\ufff0\034\ufff0\035" +
    "\ufff0\036\ufff0\037\ufff0\040\ufff0\042\ufff0\043\ufff0\046\ufff0" +
    "\047\ufff0\051\ufff0\001\002\000\004\055\144\001\002\000" +
    "\052\005\uffef\006\uffef\010\uffef\014\uffef\015\uffef\016\uffef" +
    "\022\uffef\030\uffef\032\uffef\033\uffef\034\uffef\035\uffef\036" +
    "\uffef\037\uffef\040\uffef\042\uffef\043\uffef\046\uffef\047\uffef" +
    "\051\uffef\001\002\000\052\005\uffee\006\uffee\010\uffee\014" +
    "\uffee\015\uffee\016\uffee\022\uffee\030\uffee\032\uffee\033\uffee" +
    "\034\uffee\035\uffee\036\uffee\037\uffee\040\uffee\042\uffee\043" +
    "\uffee\046\uffee\047\uffee\051\uffee\001\002\000\030\007\036" +
    "\012\043\017\031\020\040\024\033\027\042\050\030\052" +
    "\034\053\032\054\035\056\037\001\002\000\054\005\uffed" +
    "\006\uffed\010\uffed\014\uffed\015\uffed\016\uffed\022\uffed\030" +
    "\uffed\032\uffed\033\uffed\034\uffed\035\uffed\036\uffed\037\uffed" +
    "\040\uffed\042\uffed\043\uffed\045\133\046\uffed\047\uffed\051" +
    "\uffed\001\002\000\030\007\036\012\043\017\031\020\040" +
    "\024\033\027\042\050\030\052\034\053\032\054\035\056" +
    "\037\001\002\000\026\030\056\032\054\033\060\034\051" +
    "\035\053\036\055\037\062\040\057\047\061\051\111\001" +
    "\002\000\030\007\036\012\043\017\031\020\040\024\033" +
    "\027\042\050\030\052\034\053\032\054\035\056\037\001" +
    "\002\000\004\056\044\001\002\000\004\044\045\001\002" +
    "\000\004\055\046\001\002\000\004\026\047\001\002\000" +
    "\030\007\036\012\043\017\031\020\040\024\033\027\042" +
    "\050\030\052\034\053\032\054\035\056\037\001\002\000" +
    "\026\010\052\030\056\032\054\033\060\034\051\035\053" +
    "\036\055\037\062\040\057\047\061\001\002\000\030\007" +
    "\036\012\043\017\031\020\040\024\033\027\042\050\030" +
    "\052\034\053\032\054\035\056\037\001\002\000\030\007" +
    "\036\012\043\017\031\020\040\024\033\027\042\050\030" +
    "\052\034\053\032\054\035\056\037\001\002\000\030\007" +
    "\036\012\043\017\031\020\040\024\033\027\042\050\030" +
    "\052\034\053\032\054\035\056\037\001\002\000\030\007" +
    "\036\012\043\017\031\020\040\024\033\027\042\050\030" +
    "\052\034\053\032\054\035\056\037\001\002\000\030\007" +
    "\036\012\043\017\031\020\040\024\033\027\042\050\030" +
    "\052\034\053\032\054\035\056\037\001\002\000\030\007" +
    "\036\012\043\017\031\020\040\024\033\027\042\050\030" +
    "\052\034\053\032\054\035\056\037\001\002\000\004\056" +
    "\076\001\002\000\030\007\036\012\043\017\031\020\040" +
    "\024\033\027\042\050\030\052\034\053\032\054\035\056" +
    "\037\001\002\000\004\055\064\001\002\000\030\007\036" +
    "\012\043\017\031\020\040\024\033\027\042\050\030\052" +
    "\034\053\032\054\035\056\037\001\002\000\052\005\uffe8" +
    "\006\uffe8\010\uffe8\014\uffe8\015\uffe8\016\uffe8\022\uffe8\030" +
    "\056\032\054\033\060\034\051\035\053\036\055\037\062" +
    "\040\057\042\uffe8\043\uffe8\046\uffe8\047\061\051\uffe8\001" +
    "\002\000\004\040\065\001\002\000\004\056\066\001\002" +
    "\000\004\045\067\001\002\000\030\007\036\012\043\017" +
    "\031\020\040\024\033\027\042\050\030\052\034\053\032" +
    "\054\035\056\037\001\002\000\006\042\072\046\073\001" +
    "\002\000\032\030\056\032\054\033\060\034\051\035\053" +
    "\036\055\037\062\040\057\042\ufff2\046\ufff2\047\061\051" +
    "\ufff2\001\002\000\030\007\036\012\043\017\031\020\040" +
    "\024\033\027\042\050\030\052\034\053\032\054\035\056" +
    "\037\001\002\000\052\005\uffe4\006\uffe4\010\uffe4\014\uffe4" +
    "\015\uffe4\016\uffe4\022\uffe4\030\uffe4\032\uffe4\033\uffe4\034" +
    "\uffe4\035\uffe4\036\uffe4\037\uffe4\040\uffe4\042\uffe4\043\uffe4" +
    "\046\uffe4\047\uffe4\051\uffe4\001\002\000\032\030\056\032" +
    "\054\033\060\034\051\035\053\036\055\037\062\040\057" +
    "\042\ufff1\046\ufff1\047\061\051\ufff1\001\002\000\052\005" +
    "\uffe9\006\uffe9\010\uffe9\014\uffe9\015\uffe9\016\uffe9\022\uffe9" +
    "\030\056\032\054\033\060\034\051\035\053\036\055\037" +
    "\062\040\057\042\uffe9\043\uffe9\046\uffe9\047\061\051\uffe9" +
    "\001\002\000\004\045\077\001\002\000\030\007\036\012" +
    "\043\017\031\020\040\024\033\027\042\050\030\052\034" +
    "\053\032\054\035\056\037\001\002\000\006\042\072\046" +
    "\101\001\002\000\052\005\uffe3\006\uffe3\010\uffe3\014\uffe3" +
    "\015\uffe3\016\uffe3\022\uffe3\030\uffe3\032\uffe3\033\uffe3\034" +
    "\uffe3\035\uffe3\036\uffe3\037\uffe3\040\uffe3\042\uffe3\043\uffe3" +
    "\046\uffe3\047\uffe3\051\uffe3\001\002\000\052\005\uffe7\006" +
    "\uffe7\010\uffe7\014\uffe7\015\uffe7\016\uffe7\022\uffe7\030\056" +
    "\032\054\033\060\034\051\035\053\036\055\037\062\040" +
    "\057\042\uffe7\043\uffe7\046\uffe7\047\061\051\uffe7\001\002" +
    "\000\052\005\uffe6\006\uffe6\010\uffe6\014\uffe6\015\uffe6\016" +
    "\uffe6\022\uffe6\030\056\032\054\033\060\034\051\035\053" +
    "\036\055\037\062\040\057\042\uffe6\043\uffe6\046\uffe6\047" +
    "\061\051\uffe6\001\002\000\052\005\uffec\006\uffec\010\uffec" +
    "\014\uffec\015\uffec\016\uffec\022\uffec\030\056\032\054\033" +
    "\060\034\051\035\053\036\055\037\062\040\057\042\uffec" +
    "\043\uffec\046\uffec\047\061\051\uffec\001\002\000\052\005" +
    "\uffea\006\uffea\010\uffea\014\uffea\015\uffea\016\uffea\022\uffea" +
    "\030\056\032\054\033\060\034\051\035\053\036\055\037" +
    "\062\040\057\042\uffea\043\uffea\046\uffea\047\061\051\uffea" +
    "\001\002\000\052\005\uffdf\006\uffdf\010\uffdf\014\uffdf\015" +
    "\uffdf\016\uffdf\022\uffdf\030\056\032\054\033\060\034\051" +
    "\035\053\036\055\037\062\040\057\042\uffdf\043\uffdf\046" +
    "\uffdf\047\061\051\uffdf\001\002\000\052\005\uffeb\006\uffeb" +
    "\010\uffeb\014\uffeb\015\uffeb\016\uffeb\022\uffeb\030\056\032" +
    "\054\033\060\034\051\035\053\036\055\037\062\040\057" +
    "\042\uffeb\043\uffeb\046\uffeb\047\061\051\uffeb\001\002\000" +
    "\052\005\uffe5\006\uffe5\010\uffe5\014\uffe5\015\uffe5\016\uffe5" +
    "\022\uffe5\030\056\032\054\033\060\034\051\035\053\036" +
    "\055\037\062\040\057\042\uffe5\043\uffe5\046\uffe5\047\061" +
    "\051\uffe5\001\002\000\004\043\112\001\002\000\006\051" +
    "\ufff9\056\ufff9\001\002\000\026\022\114\030\056\032\054" +
    "\033\060\034\051\035\053\036\055\037\062\040\057\047" +
    "\061\001\002\000\004\056\115\001\002\000\004\044\126" +
    "\001\002\000\006\021\120\056\117\001\002\000\004\044" +
    "\121\001\002\000\052\005\uffde\006\uffde\010\uffde\014\uffde" +
    "\015\uffde\016\uffde\022\uffde\030\uffde\032\uffde\033\uffde\034" +
    "\uffde\035\uffde\036\uffde\037\uffde\040\uffde\042\uffde\043\uffde" +
    "\046\uffde\047\uffde\051\uffde\001\002\000\004\055\122\001" +
    "\002\000\004\023\123\001\002\000\030\007\036\012\043" +
    "\017\031\020\040\024\033\027\042\050\030\052\034\053" +
    "\032\054\035\056\037\001\002\000\026\030\056\032\054" +
    "\033\060\034\051\035\053\036\055\037\062\040\057\043" +
    "\125\047\061\001\002\000\006\021\uffda\056\uffda\001\002" +
    "\000\004\055\127\001\002\000\004\023\130\001\002\000" +
    "\030\007\036\012\043\017\031\020\040\024\033\027\042" +
    "\050\030\052\034\053\032\054\035\056\037\001\002\000" +
    "\026\030\056\032\054\033\060\034\051\035\053\036\055" +
    "\037\062\040\057\043\132\047\061\001\002\000\006\021" +
    "\uffdb\056\uffdb\001\002\000\030\007\036\012\043\017\031" +
    "\020\040\024\033\027\042\050\030\052\034\053\032\054" +
    "\035\056\037\001\002\000\006\042\072\046\135\001\002" +
    "\000\052\005\uffe2\006\uffe2\010\uffe2\014\uffe2\015\uffe2\016" +
    "\uffe2\022\uffe2\030\uffe2\032\uffe2\033\uffe2\034\uffe2\035\uffe2" +
    "\036\uffe2\037\uffe2\040\uffe2\042\uffe2\043\uffe2\046\uffe2\047" +
    "\uffe2\051\uffe2\001\002\000\026\016\137\030\056\032\054" +
    "\033\060\034\051\035\053\036\055\037\062\040\057\047" +
    "\061\001\002\000\030\007\036\012\043\017\031\020\040" +
    "\024\033\027\042\050\030\052\034\053\032\054\035\056" +
    "\037\001\002\000\026\005\141\030\056\032\054\033\060" +
    "\034\051\035\053\036\055\037\062\040\057\047\061\001" +
    "\002\000\030\007\036\012\043\017\031\020\040\024\033" +
    "\027\042\050\030\052\034\053\032\054\035\056\037\001" +
    "\002\000\026\006\143\030\056\032\054\033\060\034\051" +
    "\035\053\036\055\037\062\040\057\047\061\001\002\000" +
    "\052\005\uffe1\006\uffe1\010\uffe1\014\uffe1\015\uffe1\016\uffe1" +
    "\022\uffe1\030\uffe1\032\uffe1\033\uffe1\034\uffe1\035\uffe1\036" +
    "\uffe1\037\uffe1\040\uffe1\042\uffe1\043\uffe1\046\uffe1\047\uffe1" +
    "\051\uffe1\001\002\000\052\005\uffdd\006\uffdd\010\uffdd\014" +
    "\uffdd\015\uffdd\016\uffdd\022\uffdd\030\uffdd\032\uffdd\033\uffdd" +
    "\034\uffdd\035\uffdd\036\uffdd\037\uffdd\040\uffdd\042\uffdd\043" +
    "\uffdd\046\uffdd\047\uffdd\051\uffdd\001\002\000\026\014\146" +
    "\030\056\032\054\033\060\034\051\035\053\036\055\037" +
    "\062\040\057\047\061\001\002\000\030\007\036\012\043" +
    "\017\031\020\040\024\033\027\042\050\030\052\034\053" +
    "\032\054\035\056\037\001\002\000\026\015\150\030\056" +
    "\032\054\033\060\034\051\035\053\036\055\037\062\040" +
    "\057\047\061\001\002\000\052\005\uffe0\006\uffe0\010\uffe0" +
    "\014\uffe0\015\uffe0\016\uffe0\022\uffe0\030\uffe0\032\uffe0\033" +
    "\uffe0\034\uffe0\035\uffe0\036\uffe0\037\uffe0\040\uffe0\042\uffe0" +
    "\043\uffe0\046\uffe0\047\uffe0\051\uffe0\001\002\000\006\042" +
    "\072\051\152\001\002\000\052\005\uffdc\006\uffdc\010\uffdc" +
    "\014\uffdc\015\uffdc\016\uffdc\022\uffdc\030\uffdc\032\uffdc\033" +
    "\uffdc\034\uffdc\035\uffdc\036\uffdc\037\uffdc\040\uffdc\042\uffdc" +
    "\043\uffdc\046\uffdc\047\uffdc\051\uffdc\001\002\000\004\044" +
    "\154\001\002\000\004\055\155\001\002\000\006\042\ufff4" +
    "\046\ufff4\001\002\000\004\043\157\001\002\000\006\051" +
    "\ufffa\056\ufffa\001\002\000\006\044\163\045\164\001\002" +
    "\000\004\043\162\001\002\000\006\002\ufffb\004\ufffb\001" +
    "\002\000\004\055\174\001\002\000\010\042\ufff3\046\ufff3" +
    "\056\020\001\002\000\006\042\023\046\166\001\002\000" +
    "\004\044\167\001\002\000\004\055\170\001\002\000\004" +
    "\050\171\001\002\000\030\007\036\012\043\017\031\020" +
    "\040\024\033\027\042\050\030\052\034\053\032\054\035" +
    "\056\037\001\002\000\026\030\056\032\054\033\060\034" +
    "\051\035\053\036\055\037\062\040\057\047\061\051\173" +
    "\001\002\000\006\051\ufff7\056\ufff7\001\002\000\004\043" +
    "\175\001\002\000\006\051\ufff8\056\ufff8\001\002\000\006" +
    "\051\ufff6\056\014\001\002\000\004\055\200\001\002\000" +
    "\004\050\201\001\002\000\006\051\ufff6\056\014\001\002" +
    "\000\006\051\203\056\160\001\002\000\004\043\204\001" +
    "\002\000\006\002\ufffc\004\ufffc\001\002\000\006\051\206" +
    "\056\160\001\002\000\004\043\207\001\002\000\006\002" +
    "\ufffd\004\ufffd\001\002\000\004\002\000\001\002\000\006" +
    "\002\ufffe\004\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\207\000\010\002\004\003\003\004\005\001\001\000" +
    "\004\004\210\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\006\012\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\007\016\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\010\040\001\001\000\006\010\070" +
    "\011\150\001\001\000\004\010\144\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\010\135\001\001\000\002\001\001\000\004\010" +
    "\112\001\001\000\002\001\001\000\004\010\107\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\010\047\001\001\000\002\001\001" +
    "\000\004\010\106\001\001\000\004\010\105\001\001\000" +
    "\004\010\104\001\001\000\004\010\103\001\001\000\004" +
    "\010\102\001\001\000\004\010\101\001\001\000\002\001" +
    "\001\000\004\010\074\001\001\000\002\001\001\000\004" +
    "\010\062\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\010\070\011\067" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\010" +
    "\073\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\010\070\011\077\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\012" +
    "\115\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\010\123\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\010" +
    "\130\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\010\070\011\133\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\010\137\001\001\000\002" +
    "\001\001\000\004\010\141\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\010\146\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\007\164\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\010\171\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\006\204" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\006" +
    "\201\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$CoolParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$CoolParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$CoolParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    int omerrs = 0;

    public void syntax_error(Symbol cur_token) {
        int lineno = action_obj.curr_lineno();
        String filename = action_obj.curr_filename().getString();
        System.err.print("\"" + filename + "\", line " + lineno + 
                 ": parse error at or near ");
        Utilities.printToken(cur_token);
        omerrs++;
        if (omerrs>50) {
            System.err.println("More than 50 errors");
            System.exit(1);
        }
    }

    public void unrecovered_syntax_error(Symbol cur_token) {
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$CoolParser$actions {

 

    int curr_lineno() {
    return ((CoolTokenLexer)parser.getScanner()).curr_lineno();
    }

    AbstractSymbol curr_filename() {
    return ((CoolTokenLexer)parser.getScanner()).curr_filename();
    }

  private final CoolParser parser;

  /** Constructor */
  CUP$CoolParser$actions(CoolParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$CoolParser$do_action(
    int                        CUP$CoolParser$act_num,
    java_cup.runtime.lr_parser CUP$CoolParser$parser,
    java.util.Stack            CUP$CoolParser$stack,
    int                        CUP$CoolParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$CoolParser$result;

      /* select the action based on the action number */
      switch (CUP$CoolParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // dummy_feature_list ::= 
            {
              Features RESULT =null;
		 RESULT = new Features(curr_lineno()); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("dummy_feature_list",3, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // case_list ::= case_list OBJECTID COLON TYPEID DARROW expr SEMI 
            {
              Cases RESULT =null;
		Cases cl = (Cases)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-6)).value;
		AbstractSymbol id = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-5)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = cl.appendElement(new branch(curr_lineno(), id, t, e)); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("case_list",8, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // case_list ::= OBJECTID COLON TYPEID DARROW expr SEMI 
            {
              Cases RESULT =null;
		AbstractSymbol id = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-5)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = (new Cases(curr_lineno())).appendElement(new branch(curr_lineno(), id, t, e)); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("case_list",8, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr ::= LBRACE expr_list RBRACE 
            {
              Expression RESULT =null;
		Expressions el = (Expressions)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new block(curr_lineno(), el); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr ::= NEW TYPEID 
            {
              Expression RESULT =null;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new new_(curr_lineno(), t); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr ::= CASE expr OF case_list ESAC 
            {
              Expression RESULT =null;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Cases cl = (Cases)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new typcase(curr_lineno(), e, cl); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr ::= LET OBJECTID COLON TYPEID ASSIGN expr IN expr 
            {
              Expression RESULT =null;
		AbstractSymbol id = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-6)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		Expression i = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new let(curr_lineno(), id, t, i, e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expr ::= WHILE expr LOOP expr POOL 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new loop(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expr ::= IF expr THEN expr ELSE expr FI 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-5)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expression e3 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new cond(curr_lineno(), e1, e2, e3); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expr ::= OBJECTID LPAREN expr_list RPAREN 
            {
              Expression RESULT =null;
		AbstractSymbol id = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expressions el = (Expressions)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new dispatch(curr_lineno(), new object(curr_lineno(), AbstractTable.idtable.addString("self")), id, el); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expr ::= expr DOT OBJECTID LPAREN expr_list RPAREN 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-5)).value;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expressions el = (Expressions)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new dispatch(curr_lineno(), e1, o, el); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expr ::= expr AT TYPEID DOT OBJECTID LPAREN expr_list RPAREN 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-7)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-5)).value;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expressions el = (Expressions)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new static_dispatch(curr_lineno(), e1, t, o, el); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr ::= NOT expr 
            {
              Expression RESULT =null;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new comp(curr_lineno(), e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expr ::= expr EQ expr 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new eq(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr ::= expr LE expr 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new leq(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expr ::= expr LT expr 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new lt(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expr ::= expr DIV expr 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new divide(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expr ::= expr MULT expr 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new mul(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expr ::= expr MINUS expr 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new sub(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expr ::= expr PLUS expr 
            {
              Expression RESULT =null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new plus(curr_lineno(), e1, e2); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expr ::= OBJECTID 
            {
              Expression RESULT =null;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new object(curr_lineno(), o); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expr ::= BOOL_CONST 
            {
              Expression RESULT =null;
		Boolean b = (Boolean)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new bool_const(curr_lineno(), b); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expr ::= STR_CONST 
            {
              Expression RESULT =null;
		AbstractSymbol s = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new string_const(curr_lineno(), s); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expr ::= INT_CONST 
            {
              Expression RESULT =null;
		AbstractSymbol i = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new int_const(curr_lineno(), i); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr",6, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expr_list ::= expr_list COMMA expr 
            {
              Expressions RESULT =null;
		Expressions el = (Expressions)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = el.appendElement(e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr_list",7, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expr_list ::= expr 
            {
              Expressions RESULT =null;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = (new Expressions(curr_lineno())).appendElement(e); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("expr_list",7, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // formal_list ::= 
            {
              Formals RESULT =null;
		 RESULT = new Formals(curr_lineno()); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("formal_list",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // formal_list ::= formal_list COMMA OBJECTID COLON TYPEID 
            {
              Formals RESULT =null;
		Formals fl = (Formals)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = fl.appendElement(new formalc(curr_lineno(), n, t)); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("formal_list",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // formal_list ::= OBJECTID COLON TYPEID 
            {
              Formals RESULT =null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = (new Formals(curr_lineno())).appendElement(new formalc(curr_lineno(), n, t)); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("formal_list",5, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // feature_list ::= 
            {
              Features RESULT =null;
		 RESULT = new Features(curr_lineno()); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("feature_list",4, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // feature_list ::= feature_list OBJECTID LPAREN formal_list RPAREN COLON TYPEID LBRACE expr RBRACE 
            {
              Features RESULT =null;
		Features fl = (Features)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-9)).value;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-8)).value;
		Formals fl2 = (Formals)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-6)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = fl.appendElement(
            new method(curr_lineno(), n, fl2, t, e)); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("feature_list",4, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // feature_list ::= feature_list OBJECTID COLON TYPEID SEMI 
            {
              Features RESULT =null;
		Features fl = (Features)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = fl.appendElement(
            new attr(curr_lineno(), n, t, new no_expr(curr_lineno()))); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("feature_list",4, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // feature_list ::= OBJECTID LPAREN formal_list RPAREN COLON TYPEID LBRACE expr RBRACE SEMI 
            {
              Features RESULT =null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-9)).value;
		Formals fl = (Formals)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-7)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		 RESULT = (new Features(curr_lineno())).appendElement(
            new method(curr_lineno(), n, fl, t, e)); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("feature_list",4, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // feature_list ::= OBJECTID COLON TYPEID SEMI 
            {
              Features RESULT =null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = (new Features(curr_lineno())).appendElement(
            new attr(curr_lineno(), n, t, new no_expr(curr_lineno()))); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("feature_list",4, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // class ::= CLASS error LBRACE feature_list RBRACE SEMI 
            {
              class_c RESULT =null;
		Features f = (Features)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;

              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("class",2, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // class ::= CLASS TYPEID INHERITS TYPEID LBRACE feature_list RBRACE SEMI 
            {
              class_c RESULT =null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-6)).value;
		AbstractSymbol p = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		Features f = (Features)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		 RESULT = new class_c(curr_lineno(), n, p, f, curr_filename()); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("class",2, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // class ::= CLASS TYPEID LBRACE feature_list RBRACE SEMI 
            {
              class_c RESULT =null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		Features f = (Features)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		 RESULT = new class_c(curr_lineno(), n, 
                           AbstractTable.idtable.addString("Object"), 
                   f, curr_filename()); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("class",2, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // class_list ::= class_list class 
            {
              Classes RESULT =null;
		Classes cl = (Classes)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		class_c c = (class_c)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = cl.appendElement(c); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("class_list",1, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // class_list ::= class 
            {
              Classes RESULT =null;
		class_c c = (class_c)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = (new Classes(curr_lineno())).appendElement(c); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("class_list",1, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		programc start_val = (programc)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		RESULT = start_val;
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("$START",0, RESULT);
            }
          /* ACCEPT */
          CUP$CoolParser$parser.done_parsing();
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= class_list 
            {
              programc RESULT =null;
		Classes cl = (Classes)((java_cup.runtime.Symbol) CUP$CoolParser$stack.peek()).value;
		 RESULT = new programc(curr_lineno(), cl); 
              CUP$CoolParser$result = parser.getSymbolFactory().newSymbol("program",0, RESULT);
            }
          return CUP$CoolParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

